[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff-check"
entry = "uv run ruff check --fix --exit-non-zero-on-fix --show-fixes"
language = "system"
types = ["python"]

[[repos.hooks]]
id = "ruff-format"
name = "ruff-format"
entry = "uv run ruff format"
language = "system"
types = ["python"]

[[repos.hooks]]
id = "ty"
name = "ty"
entry = "uv run ty check"
language = "system"
pass_filenames = false

[[repos.hooks]]
id = "pyright-verifytypes"
name = "pyright-verifytypes"
entry = "uv run --all-extras pyright --ignoreexternal --verifytypes stickynote"
language = "system"
pass_filenames = false
