[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stickynote"
version = "0.1.0"
description = "Distributed function memoization"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "typing-extensions>=4.13.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pyright>=1.1.398",
    "pytest>=8.3.5",
    "ruff>=0.11.4",
]
